-- ============================================================
-- Atlas Research v1 — Supabase Schema
-- Run this SQL in the Supabase Dashboard SQL Editor
-- ============================================================

-- 1. Research Sessions
-- One row per research request submitted by a user.
CREATE TABLE IF NOT EXISTS research_sessions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  question    TEXT        NOT NULL,
  status      TEXT        NOT NULL DEFAULT 'draft',  -- draft | partial | complete | failed
  version     INTEGER     NOT NULL DEFAULT 1,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Research Jobs
-- Tracks the Celery background task for each session.
CREATE TABLE IF NOT EXISTS research_jobs (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  UUID        NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
  status      TEXT        NOT NULL DEFAULT 'queued', -- queued | running | completed | failed
  progress    INTEGER     NOT NULL DEFAULT 0,         -- 0 to 100
  step        TEXT        NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Decision Documents
-- The final structured decision artifact generated by the AI pipeline.
CREATE TABLE IF NOT EXISTS decision_documents (
  id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id              UUID        NOT NULL REFERENCES research_sessions(id) ON DELETE CASCADE,
  question                TEXT        NOT NULL,
  executive_summary       TEXT        NOT NULL DEFAULT '',
  recommendation_context  TEXT        NOT NULL DEFAULT '',
  tradeoffs               TEXT        NOT NULL DEFAULT '',
  alternatives            TEXT        NOT NULL DEFAULT '',
  confidence              JSONB       NOT NULL DEFAULT '{}', -- { evidence_coverage, source_quality, contradiction_risk, decision_confidence }
  version                 INTEGER     NOT NULL DEFAULT 1,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_research_jobs_session_id    ON research_jobs (session_id);
CREATE INDEX IF NOT EXISTS idx_decision_documents_session  ON decision_documents (session_id);
