import markdown
import logging
from fastapi import HTTPException
from api.schemas.export import ExportDocument
from services.export.markdown_renderer import MarkdownRenderer

logger = logging.getLogger(__name__)

try:
    from weasyprint import HTML, CSS
    WEASYPRINT_AVAILABLE = True
except (ImportError, OSError) as e:
    logger.warning(f"WeasyPrint could not be loaded. PDF export will be disabled. Error: {e}")
    WEASYPRINT_AVAILABLE = False

class PDFRenderer:
    def __init__(self):
        self.md_renderer = MarkdownRenderer()
        if WEASYPRINT_AVAILABLE:
            self.css = CSS(string='''
            @page {
                size: A4;
                margin: 2cm;
                @bottom-right {
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 9pt;
                    color: #666;
                }
                @bottom-left {
                    content: "Generated by Atlas Export System";
                    font-size: 9pt;
                    color: #666;
                }
            }
            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
                line-height: 1.6;
                color: #333;
            }
            h1, h2, h3 { 
                color: #111; 
                margin-top: 1.5em;
            }
            h1 { 
                border-bottom: 2px solid #eaecef; 
                padding-bottom: 0.3em; 
            }
            code {
                background-color: #f6f8fa;
                padding: 0.2em 0.4em;
                border-radius: 3px;
                font-family: ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace;
                font-size: 85%;
            }
            pre code {
                display: block;
                padding: 1em;
                overflow-x: auto;
                background: #f6f8fa;
                border: 1px solid #e1e4e8;
                page-break-inside: avoid;
            }
            table {
                border-collapse: collapse;
                width: 100%;
                margin: 1em 0;
            }
            th, td {
                border: 1px solid #dfe2e5;
                padding: 6px 13px;
            }
            th {
                background-color: #f6f8fa;
            }
        ''')
        else:
            self.css = None

    def render(self, doc: ExportDocument) -> bytes:
        if not WEASYPRINT_AVAILABLE:
            raise HTTPException(
                status_code=503,
                detail="PDF rendering is currently unavailable on this server due to missing system dependencies (GTK3/Pango)."
            )
            
        # 1. Generate markdown string
        md_content = self.md_renderer.render(doc)
        
        # 2. Convert markdown to HTML (enable tables, fenced code blocks)
        html_content = markdown.markdown(md_content, extensions=['fenced_code', 'tables'])
        
        # 3. Wrap in a standard HTML 5 template
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{doc.title}</title>
        </head>
        <body>
            {html_content}
        </body>
        </html>
        """
        
        # 4. Render to PDF byte stream using WeasyPrint
        pdf_bytes = HTML(string=full_html).write_pdf(stylesheets=[self.css])
        return pdf_bytes
